### ISSUE TITLE
test

### ISSUE THREAD

**Issue by LoveSimons** [wandoucao/BDCN#1]
Hello, I am very interested in your research, thank you for sharing the code, I have a small question I would like to ask you, about bsds500/HED-BSDS/test_pair.ls, I did not find about 'test_pair.lst',  and I only found test.lst,can you give me some help?
I look forward to your reply and wish you a happy life.

**Comment by wandoucao** [comment]
Hi, thank you for your interest in this research. The test_pair.lst is mainly to cater to the test code. You can modify  the code or fill in the label position of test_pair.lst directly with the information of the test image. That's what I did, because labels are not used in the test.py in the fact.

**Comment by LoveSimons** [comment]
Thank you for your reply, I tested the test.py script and I got an error with the following error:
[1]runfile('/home/renxue/BDCN-master/test.py', wdir='/home/renxue/BDCN-master')
Reloaded modules: ablation, ablation_vgg16_c, datasets, datasets.dataset, cfg
Time.struct_time(tm_year=2019, tm_mon=7, tm_mday=8, tm_hour=17, tm_min=51, tm_sec=41, tm_wday=0, tm_yday=189, tm_isdst=0)
200 200
Traceback (most recent call last):

  File "<ipython-input-3-b8d105510adb>", line 1, in <module>
    Runfile('/home/renxue/BDCN-master/test.py', wdir='/home/renxue/BDCN-master')

  File "/home/renxue/anaconda3/envs/3d-AAE/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    Execfile(filename, namespace)

  File "/home/renxue/anaconda3/envs/3d-AAE/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    Exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/renxue/BDCN-master/test.py", line 95, in <module>
    Main()

  File "/home/renxue/BDCN-master/test.py", line 76, in main
    Test(model, args)

  File "/home/renxue/BDCN-master/test.py", line 48, in test
    For i, (data, _) in enumerate(testloader):

  File "/home/renxue/anaconda3/envs/3d-AAE/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    Batch = self.collate_fn([self.dataset[i] for i in indices])

  File "/home/renxue/anaconda3/envs/3d-AAE/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    Batch = self.collate_fn([self.dataset[i] for i in indices])

  File "/home/renxue/BDCN-master/datasets/dataset.py", line 54, in __getitem__
    Gt_file = self.root + data_file[1]

IndexError: list index out of range
The test phase should not require a label image. How can I modify the test code to get the final fusion result?
I look forward to your reply

**Comment by wandoucao** [comment]
You need to change the code in datasets/dataset.py.you can tansfer a state parameter in the initialization function  of  Data class and make phase judgment in the __getitem__() ,transform() etc.
eg:
 class Data(data.Dataset):

    def __init__(self, root, lst, yita=0.5, mean_bgr=np.array([104.00699, 116.66877, 122.67892, 125.0]), crop_size=None,
                 rgb=True, scale=None, state='train'):
        self.state = state
        ...
    def __getitem__(self, index):
        data_file = self.files[index]
        # load Image
        img_file = self.root + data_file[0]
        # print(img_file)
        if not os.path.exists(img_file):
            img_file = img_file.replace('jpg', 'png')
        # img = Image.open(img_file)
        img = load_image_with_cache(img_file, self.cache)
        # load gt image
        if self.state=="train":
            gt_file = self.root + data_file[1]
            # gt = Image.open(gt_file)
            gt = load_image_with_cache(gt_file, self.cache)
            if gt.mode == '1':
                gt = gt.convert('L')
            return self.transform(img, gt)
        return self.transform(img)

**Comment by LoveSimons** [comment]
> You need to change the code in datasets/dataset.py.you can tansfer a state parameter in the initialization function of Data class and make phase judgment in the **getitem**() ,transform() etc.
> eg:
> class Data(data.Dataset):
> 
> ```
> def __init__(self, root, lst, yita=0.5, mean_bgr=np.array([104.00699, 116.66877, 122.67892, 125.0]), crop_size=None,
>              rgb=True, scale=None, state='train'):
>     self.state = state
>     ...
> def __getitem__(self, index):
>     data_file = self.files[index]
>     # load Image
>     img_file = self.root + data_file[0]
>     # print(img_file)
>     if not os.path.exists(img_file):
>         img_file = img_file.replace('jpg', 'png')
>     # img = Image.open(img_file)
>     img = load_image_with_cache(img_file, self.cache)
>     # load gt image
>     if self.state=="train":
>         gt_file = self.root + data_file[1]
>         # gt = Image.open(gt_file)
>         gt = load_image_with_cache(gt_file, self.cache)
>         if gt.mode == '1':
>             gt = gt.convert('L')
>         return self.transform(img, gt)
>     return self.transform(img)
> ```

Thank you very much for your reply. After your guidance, I  got the final fusion result. In addition, I still have a small question to ask you. For the three evaluation indicators used in the article, ODS, OIS, AP, the code does not involve calculating these three indicators, how do you calculate these three indicators? Can you share the tools for calculating indicators?
 look forward to your reply

**Comment by caihongzhiyue01** [comment]
> Hello, I am very interested in your research, thank you for sharing the code, I have a small question I would like to ask you, about bsds500/HED-BSDS/test_pair.ls, I did not find about 'test_pair.lst', and I only found test.lst,can you give me some help?
> I look forward to your reply and wish you a happy life.

I am sorry to bother you. But are you realizing the source code? I want  to use the pretrained  the module to obtain the edge information on other dataset.
